version: 1
disable_existing_loggers: false
formatters:
  simple:
    class: src.interface.logging.logger.ColoredTerminalFormatter
  verbose:
    class: src.interface.logging.logger.VerboseFormatter
  json:
    "()": src.interface.logging.logger.MyJSONFormatter
    fmt_keys:
      level: levelname
      logger: name
      module: module
      thread_name: threadName
      function: funcName
      line: lineno
      timestamp: timestamp
      message: message
filters:
  main_filter:
    class: logging.Filter
    name: main_logger
  control_filter:
    class: logging.Filter
    name: control_logger
  imu_filter:
    class: logging.Filter
    name: imu_logger
  interface_filter:
    class: logging.Filter
    name: interface_logger
  kws_filter:
    class: logging.Filter
    name: kws_logger
  lights_filter:
    class: logging.Filter
    name: lights_logger
  maestro_filter:
    class: logging.Filter
    name: maestro_logger
  robot_filter:
    class: logging.Filter
    name: robot_logger
  odas_filter:
    class: logging.Filter
    name: odas_logger
  gait_generator_filter:
    class: logging.Filter
    name: gait_generator_logger
  gamepad_filter:
    class: logging.Filter
    name: gamepad_logger
  button_filter:
    class: logging.Filter
    name: button_logger
handlers:
  stdout:
    class: logging.StreamHandler
    level: USER_INFO
    formatter: simple
    stream: ext://sys.stdout
  stderr:
    class: logging.StreamHandler
    level: WARNING
    formatter: simple
    stream: ext://sys.stderr
  main_logger:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: verbose
    filename: main.log
    maxBytes: 10485760 # 10MB
    backupCount: 5
    filters:
      - main_filter
  control_logger:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: verbose
    filename: control.log
    maxBytes: 10485760 # 10MB
    backupCount: 5
    filters:
      - control_filter
  imu_logger:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: verbose
    filename: imu.log
    maxBytes: 10485760 # 10MB
    backupCount: 5
    filters:
      - imu_filter
  interface_logger:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: verbose
    filename: interface.log
    maxBytes: 10485760 # 10MB
    backupCount: 5
    filters:
      - interface_filter
  kws_logger:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: verbose
    filename: kws.log
    maxBytes: 10485760 # 10MB
    backupCount: 5
    filters:
      - kws_filter
  lights_logger:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: verbose
    filename: lights.log
    maxBytes: 10485760 # 10MB
    backupCount: 5
    filters:
      - lights_filter
  maestro_logger:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: verbose
    filename: maestro.log
    maxBytes: 10485760 # 10MB
    backupCount: 5
    filters:
      - maestro_filter
  robot_logger:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: verbose
    filename: robot.log
    maxBytes: 10485760 # 10MB
    backupCount: 5
    filters:
      - robot_filter
  odas_logger:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: verbose
    filename: odas.log
    maxBytes: 10485760 # 10MB
    backupCount: 5
    filters:
      - odas_filter
  gait_generator_logger:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: verbose
    filename: gait_generator.log
    maxBytes: 10485760 # 10MB
    backupCount: 5
    filters:
      - gait_generator_filter
  gamepad_logger:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: verbose
    filename: gamepad.log
    maxBytes: 10485760 # 10MB
    backupCount: 5
    filters:
      - gamepad_filter
  button_logger:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: verbose
    filename: button.log
    maxBytes: 10485760 # 10MB
    backupCount: 5
    filters:
      - button_filter
  queue_handler:
    class: logging.handlers.QueueHandler
    level: DEBUG
    handlers:
      - stdout
      - main_logger
      - control_logger
      - imu_logger
      - interface_logger
      - kws_logger
      - lights_logger
      - maestro_logger
      - robot_logger
      - odas_logger
      - gait_generator_logger
      - gamepad_logger
      - button_logger
    respect_handler_level: true
loggers:
  root:
    level: DEBUG
    handlers:
      - queue_handler
  main_logger:
    level: DEBUG
    handlers:
      - queue_handler
    propagate: false
  control_logger:
    level: DEBUG
    handlers:
      - queue_handler
    propagate: false
  imu_logger:
    level: DEBUG
    handlers:
      - queue_handler
    propagate: false
  interface_logger:
    level: DEBUG
    handlers:
      - queue_handler
    propagate: false
  kws_logger:
    level: DEBUG
    handlers:
      - queue_handler
    propagate: false
  lights_logger:
    level: DEBUG
    handlers:
      - queue_handler
    propagate: false
  maestro_logger:
    level: DEBUG
    handlers:
      - queue_handler
    propagate: false
  robot_logger:
    level: DEBUG
    handlers:
      - queue_handler
    propagate: false
  odas_logger:
    level: DEBUG
    handlers:
      - queue_handler
    propagate: false
  gait_generator_logger:
    level: DEBUG
    handlers:
      - queue_handler
    propagate: false
  gamepad_logger:
    level: DEBUG
    handlers:
      - queue_handler
    propagate: false
  button_logger:
    level: DEBUG
    handlers:
      - queue_handler
    propagate: false